# filename: config.yaml
seed_everything: 42

data:
  class_path: mypackage.dataloader.MNISTDataModule
  init_args:
    batch_size: 64

model:
  class_path: mypackage.model.LitMNIST
  init_args: {}

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.01

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.1

trainer:
  logger: true
  ## Custom loggers
  # - class_path: pytorch_lightning.loggers.CSVLogger
  #   init_args:
  #     save_dir: 'saved'
  #     name: 'csv'
  # - class_path: pytorch_lightning.loggers.TensorBoardLogger
  #   init_args:
  #     save_dir: 'saved'
  #     name: 'tb'
  enable_checkpointing: true
  callbacks: null
  ## Custom callbacks
  # - class_path: pytorch_lightning.callbacks.ModelCheckpoint
  #   init_args:
  #     # dirpath: 'saved/ckpt'
  #     filename: '{epoch}-{step}-{loss:.4f}-v{v_num}'
  #     auto_insert_metric_name: false
  default_root_dir: '/home/data'
  process_position: 0
  num_nodes: 1
  num_processes: 1
  auto_select_gpus: false
  enable_progress_bar: false
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  max_steps: -1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  num_sanity_val_steps: 2
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  amp_backend: native
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
